import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { join } from 'node:path';
import { loadArticles } from './markdown.mjs';

const root = new URL('../', import.meta.url).pathname.replace(/^\/(.:)/, '$1');
const readJson = async (path) => JSON.parse(await readFile(join(root, path), 'utf8'));
const readJsonOptional = async (path, fallback) => { try { return await readJson(path); } catch { return fallback; } };
const esc = (s='') => String(s).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const site = await readJson('config/site.json');
const urgent = await readJson('content/urgent.json');
const legacyNews = await readJson('content/news.json');
const markdownNews = (await loadArticles(root)).filter(article=>article.status==='published').map(article=>article.image?{...article,bodyHtml:`<figure class="featured-image"><img src="${esc(article.image)}" alt="${esc(article.imageAlt||'')}" loading="eager" style="max-width:100%;height:auto"></figure>${article.bodyHtml}`} : article);
const news = [...legacyNews.map(item=>({...item,bodyText:(item.body||[]).join(' ')})),...markdownNews].sort((a,b)=>b.date.localeCompare(a.date));
const agreement = await readJson('content/agreement.json');
const safety = await readJson('content/safety.json');
const surveys = await readJson('content/surveys.json');
const events = await readJson('content/events.json');
const tracking = await readJson('content/tracking.json');
const externalNews = await readJsonOptional('content/.generated/external-news.json', []);
const ingestion = await readJsonOptional('content/.generated/ingestion-status.json', { generatedAt: null });
const out = join(root, 'dist');
const basePath = (site.basePath || '').replace(/\/$/, '');
const link = (value='') => /^https?:\/\//.test(value) ? value : `${basePath}${value.startsWith('/') ? value : `/${value}`}`;
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

const nav = `<nav aria-label="Principal"><a href="${link('/')}">Inicio</a><a href="${link('/ahora/')}">Ahora</a><a href="${link('/noticias/')}">Noticias</a><a href="${link('/convenio/')}">Convenio</a><a href="${link('/seguridad/')}">Seguridad</a><a href="${link('/encuestas/')}">Encuestas</a><a href="${link('/buscar/')}">Buscar</a><a href="${link('/contacto/')}">Contacto</a></nav>`;
const banner = urgent.active ? `<aside class="urgent ${esc(urgent.level)}" data-start="${esc(urgent.starts)}" data-end="${esc(urgent.ends)}"><strong>${esc(urgent.title)}</strong><span>${esc(urgent.message)}</span><a href="${esc(link(urgent.url))}">Más información</a></aside>` : '';
const layout = (title, body, description=site.description) => `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · ${esc(site.shortName)}</title><meta name="description" content="${esc(description)}"><link rel="alternate" type="application/rss+xml" href="${link('/feed.xml')}" title="Noticias"><link rel="stylesheet" href="${link('/assets/style.css')}"></head><body>${banner}<header><a class="brand" href="${link('/')}">${esc(site.name)}</a>${nav}</header><main>${body}</main><footer><p>${esc(site.name)} · Información pública y orientativa.</p><p><a href="${esc(site.links.whatsapp)}">Canal de WhatsApp</a> · <a href="${esc(site.links.n2)}">Canal N2</a></p></footer><script src="${link('/assets/app.js')}" defer></script></body></html>`;
const writePage = async (path, html) => { const dir=join(out,path); await mkdir(dir,{recursive:true}); await writeFile(join(dir,'index.html'),html); };

await writePage('', layout('Inicio', `<section class="hero"><p class="eyebrow">Información sindical útil y verificable</p><h1>Derechos, prevención y participación en un solo lugar</h1><p>${esc(site.description)}</p><div class="actions"><a class="button" href="${link('/convenio/')}">Consultar convenio</a><a class="button secondary" href="${esc(site.links.contact)}">Hablar con el comité</a></div></section><section><h2>Accesos rápidos</h2><div class="grid"><a class="card" href="${link('/seguridad/')}"><strong>Seguridad por puesto</strong><span>Riesgos, medidas y comunicación.</span></a><a class="card" href="${link('/encuestas/')}"><strong>Encuestas</strong><span>Convierte problemas cotidianos en datos agregados.</span></a><a class="card" href="${esc(site.links.n2)}"><strong>N2</strong><span>Acceso al canal externo configurado.</span></a></div></section><section><h2>Últimas noticias</h2>${news.map(n=>`<article><time>${esc(n.date)}</time><h3><a href="${link(`/noticias/${esc(n.slug)}/`)}">${esc(n.title)}</a></h3><p>${esc(n.summary)}</p></article>`).join('')}</section>`));
await writePage('noticias', layout('Noticias', `<h1>Noticias</h1><h2>San Blas</h2>${news.map(n=>`<article class="news-card news-local"><span class="source-label">Local</span><time>${esc(n.date)}</time><h3><a href="${link(`/noticias/${esc(n.slug)}/`)}">${esc(n.title)}</a></h3><p>${esc(n.summary)}</p></article>`).join('')}<h2>Actualidad sindical y jurídica</h2><p class="source-status">Actualizado: ${ingestion.generatedAt ? esc(new Date(ingestion.generatedAt).toLocaleString('es-ES',{timeZone:site.timezone})) : 'sin conexión'} · ${externalNews.length} elementos.</p><div id="external-news" class="news-stream" data-page-size="6">${externalNews.map((n,index)=>`<article class="news-card news-rss external-card" data-stream-item${index>=6?' hidden':''}><span class="source-label">RSS</span>${n.image?`<a class="article-image" href="${esc(n.url)}" rel="external noopener" tabindex="-1"><img src="${esc(n.image)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.closest('.article-image').remove()"></a>`:''}<div><span class="pill">${esc(n.source)}</span> <time>${esc(n.date.slice(0,10))}</time><h3><a href="${esc(n.url)}" rel="external noopener">${esc(n.title)}</a></h3><p>${esc(n.summary.slice(0,280))}</p></div></article>`).join('') || '<p>No se pudo actualizar la información externa. El contenido local sigue disponible.</p>'}</div>${externalNews.length>6?'<div id="stream-sentinel" aria-hidden="true"></div><button id="load-more" class="button" type="button">Cargar más noticias</button><p id="stream-status" class="source-status" aria-live="polite"></p>':''}`));
for (const n of news) await writePage(`noticias/${n.slug}`, layout(n.title, `<p><a href="${link('/noticias/')}">← Noticias</a></p><article><time>${esc(n.date)}</time><h1>${esc(n.title)}</h1>${n.author?`<p class="source-status">Por ${esc(n.author)}</p>`:''}${n.bodyHtml||(n.body||[]).map(p=>`<p>${esc(p)}</p>`).join('')}</article>`, n.summary));
await writePage('convenio', layout('Convenio', `<section class="agreement-hero"><p class="eyebrow">Consulta del convenio</p><h1>${esc(agreement.title)}</h1><div class="agreement-summary"><div><span>Estado</span><strong>${esc(agreement.status)}</strong></div><div><span>Vigencia</span><strong>${esc(agreement.validFrom)} - ${esc(agreement.validTo)}</strong></div><div><span>Código</span><strong>${esc(agreement.code)}</strong></div><div><span>Publicación</span><strong>${esc(agreement.published)}</strong></div></div><div class="actions"><a class="button" href="${esc(agreement.officialPdf)}">Abrir documento</a><a class="button secondary" href="${esc(agreement.sourceUrl)}">Ver ficha en Iberley</a></div></section><p class="notice"><strong>Importante:</strong> esta página facilita la consulta del índice. Para decisiones laborales, contrasta el artículo completo, correcciones y acuerdos posteriores con el documento publicado. Actualizado: <time>${esc(agreement.updated)}</time>.</p><section><h2>Buscar por tema o artículo</h2><label for="agreement-search">Ej.: vacaciones, jornada, incapacidad, salario</label><input id="agreement-search" class="search" type="search" autocomplete="off" placeholder="Escribe una palabra"><p id="agreement-count" aria-live="polite"></p></section><div class="agreement"><aside><h2>Índice</h2>${agreement.chapters.map(c=>`<a href="#${esc(c.id)}">${esc(c.title)}</a>`).join('')}<a href="#modificaciones">Modificaciones</a><a href="#historicos">Históricos</a></aside><div id="agreement-results">${agreement.chapters.map(c=>`<section id="${esc(c.id)}" data-agreement-chapter><h2>${esc(c.title)}</h2><div class="agreement-articles">${c.articles.map(a=>`<article id="${esc(a.id)}" data-agreement-item data-search="${esc(`${c.title} ${a.title}`.toLocaleLowerCase('es').normalize('NFD').replace(/\p{Diacritic}/gu,''))}"><h3><a class="anchor" href="#${esc(a.id)}">#</a> ${esc(a.title)}</h3><a href="${esc(agreement.sourceUrl)}">Consultar texto en la fuente</a></article>`).join('')}</div></section>`).join('')}<section id="modificaciones"><h2>Modificaciones y correcciones posteriores</h2>${agreement.amendments.map(a=>`<article><span class="pill">${esc(a.type)}</span> <time>${esc(a.date)}</time><h3>${esc(a.title)}</h3>${a.validFrom?`<p>Efectos desde: <time>${esc(a.validFrom)}</time></p>`:''}</article>`).join('')}</section><section id="historicos"><h2>Convenios históricos</h2><p>Relación orientativa desde 2009-2010. Cada versión debe consultarse en su fuente.</p><div class="history-grid">${agreement.history.map(h=>`<article><span class="pill">${esc(h.status)}</span><h3>${esc(h.period)}</h3><p>Publicado: <time>${esc(h.published)}</time></p>${h.note?`<p>${esc(h.note)}</p>`:''}<a href="${esc(h.url)}">Abrir fuente</a></article>`).join('')}</div></section></div></div>`));
await writePage('seguridad', layout('Seguridad laboral', `<h1>Seguridad laboral por puesto</h1><p>Información preventiva general. La evaluación de riesgos del puesto y las instrucciones vigentes son la referencia.</p><div class="grid">${safety.map(s=>`<a class="card" href="${link(`/seguridad/${esc(s.slug)}/`)}"><strong>${esc(s.title)}</strong><span>${s.risks.length} riesgos destacados</span></a>`).join('')}</div>`));
for (const s of safety) await writePage(`seguridad/${s.slug}`, layout(`Seguridad: ${s.title}`, `<p><a href="${link('/seguridad/')}">← Puestos</a></p><h1>${esc(s.title)}</h1><h2>Riesgos a revisar</h2><ul>${s.risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Medidas básicas</h2><ul>${s.measures.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><a class="button" href="${esc(site.links.contact)}">Comunicar al comité</a></p>`));
await writePage('encuestas', layout('Encuestas', `<h1>Encuestas</h1><p>Publicamos resultados agregados; no introduzcas datos personales o de salud en campos libres.</p>${surveys.map(s=>`<article><span class="pill">${s.status==='active'?'Activa':'Cerrada'}</span><h2>${esc(s.title)}</h2><p>${esc(s.description)}</p><a class="button" href="${esc(site.links[s.urlKey])}">Participar</a></article>`).join('')}`));
await writePage('contacto', layout('Contacto', `<h1>Contacto y canales</h1><div class="grid"><a class="card" href="${esc(site.links.contact)}"><strong>Comité</strong><span>Consulta mediante formulario.</span></a><a class="card" href="${esc(site.links.whatsapp)}"><strong>WhatsApp</strong><span>Novedades y avisos.</span></a><a class="card" href="${esc(site.links.n2)}"><strong>N2</strong><span>Canal externo configurado.</span></a></div><section class="notice"><h2>Privacidad</h2><p>No envíes afiliación sindical, salud u otros datos especialmente protegidos por canales generales. El administrador debe configurar un circuito específico antes de recogerlos.</p></section>`));
await writePage('ahora', layout('San Blas ahora', `<h1>San Blas ahora</h1><div class="stats"><div><strong>${tracking.filter(x=>x.status!=='closed').length}</strong><span>asuntos en seguimiento</span></div><div><strong>${surveys.filter(x=>x.status==='active').length}</strong><span>encuestas activas</span></div><div><strong>${events.filter(x=>new Date(x.date)>=new Date()).length}</strong><span>próximos eventos</span></div></div><h2>En seguimiento</h2>${tracking.map(x=>`<article><span class="pill">${esc(x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><time>Actualizado: ${esc(x.updated)}</time></article>`).join('')}<h2>Calendario</h2>${events.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<article><time>${esc(x.date)}</time><h3><a href="${esc(link(x.url))}">${esc(x.title)}</a></h3><p>${esc(x.description)}</p></article>`).join('')}`));
await writePage('buscar', layout('Buscar', `<h1>Buscar</h1><label for="search">Convenio, noticias, seguridad y seguimiento</label><input id="search" class="search" type="search" autocomplete="off" placeholder="Ej.: vacaciones, taquillas, jornada"><p id="search-count" aria-live="polite"></p><div id="search-results"></div>`));
await writePage('publicar', layout('Publicador Markdown', `<h1>Publicador de artículos</h1><p>Prepara un archivo Markdown para revisión. El formulario funciona únicamente en tu navegador y no envía el contenido a ningún servidor.</p><form id="publisher" data-image-library="${esc(site.publishing?.imageLibraryUrl||'')}"><label>Título<input name="title" required></label><label>Resumen<textarea name="summary" required maxlength="240"></textarea></label><div class="grid"><label>Fecha<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Autor<input name="author" value="Comité de San Blas"></label><label>Estado<select name="status"><option value="draft">Borrador</option><option value="review">En revisión</option><option value="published">Publicado</option></select></label><label>Prioridad<select name="priority"><option value="normal">Normal</option><option value="important">Importante</option><option value="urgent">Urgente</option></select></label></div><label>Etiquetas separadas por comas<input name="tags" placeholder="jornada, comité"></label><section class="media-library"><h2>Imágenes de Drive</h2><p id="image-library-status">Cargando biblioteca…</p><div id="image-library" class="image-library"></div></section><label>Contenido Markdown<textarea name="body" class="editor" required placeholder="## Apartado\n\nEscribe el artículo..."></textarea></label><div class="actions"><button class="button" type="button" id="preview-md">Vista previa</button><button class="button secondary" type="button" id="download-md">Descargar .md</button></div></form><section><h2>Vista previa</h2><article id="md-preview"><p>La vista previa aparecerá aquí.</p></article></section><p class="notice">Antes de publicar: revisa fuentes, fechas, nombres y datos personales. Un archivo con estado <code>draft</code> o <code>review</code> no aparecerá en la web.</p>`));

await mkdir(join(out,'assets'),{recursive:true});
await cp(join(root,'src/style.css'),join(out,'assets/style.css'));
await cp(join(root,'src/app.js'),join(out,'assets/app.js'));
await cp(join(root,'src/news.css'),join(out,'assets/news.css'));
await cp(join(root,'src/publisher.js'),join(out,'assets/publisher.js'));
await cp(join(root,'src/agreement.js'),join(out,'assets/agreement.js'));
await cp(join(root,'src/agreement.css'),join(out,'assets/agreement.css'));
await cp(join(root,'content/agreement-guide.json'),join(out,'agreement-guide.json'));
await cp(join(root,'content/agreement.json'),join(out,'agreement-data.json'));
await cp(join(root,'config/taxonomy.json'),join(out,'taxonomy.json'));
await cp(join(root,'config/site.json'),join(out,'site-config.json'));
await cp(join(root,'static/images'),join(out,'images'),{recursive:true});
const base = site.baseUrl.replace(/\/$/,'');
const routes = ['', 'ahora/', 'buscar/', 'publicar/', 'noticias/', ...news.map(n=>`noticias/${n.slug}/`), 'convenio/', 'seguridad/', ...safety.map(s=>`seguridad/${s.slug}/`), 'encuestas/', 'contacto/'];
await writeFile(join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${base}/${r}</loc></url>`).join('')}</urlset>`);
await writeFile(join(out,'feed.xml'),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(site.name)}</title><link>${base}</link><description>${esc(site.description)}</description>${news.map(n=>`<item><title>${esc(n.title)}</title><link>${base}/noticias/${esc(n.slug)}/</link><guid>${base}/noticias/${esc(n.slug)}/</guid><pubDate>${new Date(n.date+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(n.summary)}</description><category domain="${base}/taxonomy.json#category">${esc(n.category)}</category>${(n.tags||[]).map(tag=>`<category domain="${base}/taxonomy.json#tag">${esc(tag)}</category>`).join('')}</item>`).join('')}</channel></rss>`);
await writeFile(join(out,'feed.json'),JSON.stringify({version:'https://jsonfeed.org/version/1.1',title:site.name,home_page_url:base,feed_url:`${base}/feed.json`,_sindical:{taxonomy:`${base}/taxonomy.json`,taxonomy_version:'1.0'},items:news.map(n=>({id:`${base}/noticias/${n.slug}/`,url:`${base}/noticias/${n.slug}/`,title:n.title,summary:n.summary,date_published:`${n.date}T12:00:00Z`,tags:[n.category,...(n.tags||[])],_sindical:{category:n.category,tags:n.tags||[]}}))},null,2));
await writeFile(join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
await writeFile(join(out,'local-news.json'),JSON.stringify(news.map(n=>({slug:n.slug,image:n.image||'',imageAlt:n.imageAlt||''})),null,2));
const searchItems = [
  ...news.map(n=>({title:n.title,summary:n.summary,url:link(`/noticias/${n.slug}/`),type:'Noticia local',text:`${n.title} ${n.summary} ${n.bodyText||''}`})),
  ...externalNews.map(n=>({title:n.title,summary:n.summary,url:n.url,type:n.source,text:`${n.title} ${n.summary}`})),
  ...agreement.chapters.flatMap(c=>c.articles.map(a=>({title:a.title,summary:c.title,url:link(`/convenio/#${a.id}`),type:'Convenio',text:`${c.title} ${a.title} ${a.text||''}`}))),
  ...safety.map(s=>({title:s.title,summary:s.risks.join(' · '),url:link(`/seguridad/${s.slug}/`),type:'Seguridad',text:[s.title,...s.risks,...s.measures].join(' ')})),
  ...tracking.map(x=>({title:x.title,summary:x.summary,url:link('/ahora/'),type:'Seguimiento',text:`${x.title} ${x.summary}`}))
];
await writeFile(join(out,'search-index.json'),JSON.stringify(searchItems,null,2));
await writeFile(join(out,'admin.html'),layout('Administración',`<h1>Publicación sencilla</h1><p>Este panel no almacena credenciales. Abre los formularios y hojas configurados por el comité.</p><div class="grid"><a class="card" href="${esc(site.links.contact)}"><strong>Formulario editorial</strong><span>Crear borradores y avisos.</span></a><a class="card" href="${esc(site.links.survey)}"><strong>Encuestas</strong><span>Gestionar formularios y respuestas.</span></a></div><p class="notice">Protege las hojas fuente con permisos de Google. Publica únicamente una vista o exportación sin datos personales.</p>`));
console.log(`Built ${routes.length} pages and feeds in dist/`);
