const agreementSearch=document.querySelector('#agreement-search');
if(agreementSearch){
  const items=[...document.querySelectorAll('[data-agreement-item]')],chapters=[...document.querySelectorAll('[data-agreement-chapter]')],count=document.querySelector('#agreement-count');
  const normalize=value=>value.toLocaleLowerCase('es').normalize('NFD').replace(/\p{Diacritic}/gu,'').trim();
  const filter=()=>{const terms=normalize(agreementSearch.value).split(/\s+/).filter(Boolean);let visible=0;for(const item of items){const matches=!terms.length||terms.every(term=>item.dataset.search.includes(term));item.hidden=!matches;if(matches)visible++}for(const chapter of chapters)chapter.hidden=terms.length>0&&![...chapter.querySelectorAll('[data-agreement-item]')].some(item=>!item.hidden);count.textContent=terms.length?`${visible} artículos encontrados`:`${items.length} artículos en el índice`};
  agreementSearch.addEventListener('input',filter);filter();
  const historical=document.querySelector('#historicos');if(historical){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Consultar versiones anteriores (secundario)';details.className='agreement-history';historical.before(details);details.append(summary,historical);const note=document.createElement('p');note.textContent='No se realiza una comparación artículo por artículo entre versiones.';summary.after(note)}
  fetch('../agreement-guide.json').then(response=>response.json()).then(guide=>{const panel=document.createElement('section');panel.className='plain-language notice';panel.innerHTML=`<span class="pill">${guide.status}</span><h2>${guide.title}</h2><p>${guide.intro}</p><button class="button" type="button" id="toggle-plain">Mostrar explicaciones claras</button>`;agreementSearch.closest('section').after(panel);for(const [id,text] of Object.entries(guide.chapters)){const chapter=document.querySelector(`#${id}`);if(!chapter)continue;const explanation=document.createElement('aside');explanation.className='plain-explanation';explanation.hidden=true;explanation.innerHTML=`<h3>En palabras sencillas</h3><p>${text}</p>`;chapter.querySelector('h2').after(explanation)}const glossary=document.createElement('section');glossary.className='plain-glossary';glossary.hidden=true;glossary.innerHTML=`<h2>Palabras que pueden resultar difíciles</h2><dl>${guide.glossary.map(item=>`<div><dt>${item.term}</dt><dd>${item.meaning}</dd></div>`).join('')}</dl>`;document.querySelector('#modificaciones').before(glossary);const button=document.querySelector('#toggle-plain');button.addEventListener('click',()=>{const showing=button.getAttribute('aria-pressed')==='true';button.setAttribute('aria-pressed',String(!showing));button.textContent=showing?'Mostrar explicaciones claras':'Ocultar explicaciones claras';document.querySelectorAll('.plain-explanation').forEach(element=>element.hidden=showing);glossary.hidden=showing})}).catch(()=>{});
}
