const form=document.querySelector('#publisher');
if(form){
  const slugify=value=>value.toLocaleLowerCase('es').normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80);
  const escape=value=>String(value).replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
  const values=()=>Object.fromEntries(new FormData(form));
  const markdown=()=>{const data=values();const tags=data.tags.split(',').map(tag=>tag.trim()).filter(Boolean);return `---\ntitle: ${data.title.trim()}\nslug: ${slugify(data.title)}\ndate: ${data.date}\nsummary: ${data.summary.trim().replace(/\s+/g,' ')}\nauthor: ${data.author.trim()}\nstatus: ${data.status}\npriority: ${data.priority}\ntags: [${tags.join(', ')}]\n---\n\n${data.body.trim()}\n`};
  const render=()=>{const data=values();const body=escape(data.body).replace(/!\[([^\]]*)\]\((https:\/\/[^\s)]+)\)/g,'<figure><img src="$2" alt="$1" loading="lazy"><figcaption>$1</figcaption></figure>').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^[-*] (.+)$/gm,'<li>$1</li>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').split(/\n{2,}/).map(block=>/^<(h|li|figure)/.test(block)?block:`<p>${block.replace(/\n/g,'<br>')}</p>`).join('');document.querySelector('#md-preview').innerHTML=`<span class="pill">${escape(data.status)}</span><h2>${escape(data.title||'Sin título')}</h2><p>${escape(data.summary)}</p>${body}`};
  document.querySelector('#preview-md').addEventListener('click',render);
  document.querySelector('#download-md').addEventListener('click',()=>{if(!form.reportValidity())return;const data=values();const blob=new Blob([markdown()],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${data.date}-${slugify(data.title)}.md`;anchor.click();URL.revokeObjectURL(url)});
  const media=document.querySelector('.media-library');media.innerHTML='<h2>Insertar imagen desde Drive</h2><p>Sube la imagen a la carpeta compartida, activa «cualquiera con el enlace» y pega aquí el enlace copiado.</p><label>Enlace de Drive<input id="drive-image-url" type="url" placeholder="https://drive.google.com/file/d/…/view"></label><label>Descripción de la imagen<input id="drive-image-alt" placeholder="Personas reunidas en una asamblea"></label><button class="button" type="button" id="insert-drive-image">Insertar imagen</button><p id="drive-image-status" aria-live="polite"></p>';
  const driveUrl=value=>{try{const url=new URL(value);const id=url.pathname.match(/\/file\/d\/([^/]+)/)?.[1]||url.searchParams.get('id');return id?`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`:''}catch{return''}};
  document.querySelector('#insert-drive-image').addEventListener('click',()=>{const source=document.querySelector('#drive-image-url').value;const url=driveUrl(source);const status=document.querySelector('#drive-image-status');if(!url){status.textContent='No reconozco ese enlace de Drive.';return}const editor=form.elements.body;const alt=document.querySelector('#drive-image-alt').value.trim();editor.setRangeText(`\n![${alt}](${url})\n`,editor.selectionStart,editor.selectionEnd,'end');status.textContent='Imagen insertada en el artículo.';editor.focus();render()});
  const script=document.createElement('style');script.textContent='#publisher label{display:block;font-weight:700;margin:1rem 0}#publisher input,#publisher textarea,#publisher select{display:block;width:100%;font:inherit;padding:.7rem;margin-top:.3rem}.editor{min-height:20rem;font-family:ui-monospace,monospace}#md-preview img{max-width:100%;height:auto}';document.head.append(script);
}
