const form=document.querySelector('#publisher');
if(form){
  const editor=form.elements.body,preview=document.querySelector('#md-preview');
  const slugify=value=>value.toLocaleLowerCase('es').normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80);
  const escape=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
  const values=()=>Object.fromEntries(new FormData(form));
  const markdown=()=>{const data=values(),tags=data.tags.split(',').map(tag=>tag.trim()).filter(Boolean);return `---\ntitle: ${data.title.trim()}\nslug: ${slugify(data.title)}\ndate: ${data.date}\nsummary: ${data.summary.trim().replace(/\s+/g,' ')}\nauthor: ${data.author.trim()}\nstatus: ${data.status}\npriority: ${data.priority}\ntags: [${tags.join(', ')}]\n---\n\n${data.body.trim()}\n`};
  const inline=value=>escape(value).replace(/!\[([^\]]*)\]\((https:\/\/[^\s)]+)\)/g,'<img src="$2" alt="$1" loading="lazy">').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>');
  const renderBody=value=>{const html=[];let list=[],type='';const flush=()=>{if(list.length){html.push(`<${type}>${list.map(item=>`<li>${inline(item)}</li>`).join('')}</${type}>`);list=[];type=''}};for(const line of value.split(/\r?\n/)){if(!line.trim()){flush();continue}const heading=line.match(/^(#{2,4})\s+(.+)$/);if(heading){flush();html.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);continue}const item=line.match(/^[-*]\s+(.+)$/),numbered=line.match(/^\d+\.\s+(.+)$/);if(item||numbered){const next=item?'ul':'ol';if(type&&type!==next)flush();type=next;list.push((item||numbered)[1]);continue}flush();if(/^---+$/.test(line))html.push('<hr>');else if(line.startsWith('> [!IMPORTANTE]'))html.push(`<aside class="callout"><strong>Importante</strong>${inline(line.slice(15))}</aside>`);else if(line.startsWith('> '))html.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);else if(/^!\[/.test(line))html.push(`<figure>${inline(line)}</figure>`);else html.push(`<p>${inline(line)}</p>`)}flush();return html.join('')};
  const render=()=>{const data=values();preview.innerHTML=`<span class="pill">${escape(data.status)}</span><h2>${escape(data.title||'Sin título')}</h2><p>${escape(data.summary)}</p>${renderBody(data.body)}`};
  const format=(action,...args)=>{const start=editor.selectionStart,end=editor.selectionEnd,selected=editor.value.slice(start,end);let text=selected;if(action==='wrap')text=`${args[0]}${selected||'texto'}${args[1]}`;if(action==='heading')text=`${args[0]}${selected||'Texto del título'}`;if(action==='lines')text=(selected||'Elemento').split(/\r?\n/).map(line=>`${args[0]}${line}`).join('\n');if(action==='numbered')text=(selected||'Elemento').split(/\r?\n/).map((line,index)=>`${index+1}. ${line}`).join('\n');if(action==='link'){const url=window.prompt('Pega el enlace completo (https://…)');if(!url)return;text=`[${selected||'texto del enlace'}](${url})`}if(action==='insert')text=args[0];editor.setRangeText(text,start,end,'select');editor.focus();render()};
  const toolbar=document.createElement('div');toolbar.className='editor-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Formato del artículo');
  const tools=[['Título','heading','## '],['Subtítulo','heading','### '],['Negrita','wrap','**','**'],['Cursiva','wrap','*','*'],['Enlace','link'],['Lista','lines','- '],['Numerada','numbered'],['Cita','lines','> '],['Aviso','insert','\n> [!IMPORTANTE] Escribe aquí el aviso\n'],['Separador','insert','\n---\n']];
  for(const [label,action,...args] of tools){const button=document.createElement('button');button.type='button';button.className='editor-tool';button.textContent=label;button.addEventListener('click',()=>format(action,...args));toolbar.append(button)}editor.before(toolbar);
  document.querySelector('#preview-md').addEventListener('click',render);form.addEventListener('input',render);
  document.querySelector('#download-md').addEventListener('click',()=>{if(!form.reportValidity())return;const data=values(),blob=new Blob([markdown()],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${data.date}-${slugify(data.title)}.md`;anchor.click();URL.revokeObjectURL(url)});
  const media=document.querySelector('.media-library');media.innerHTML='<h2>Insertar imagen desde Drive</h2><p>Sube la imagen a la carpeta compartida, activa «cualquiera con el enlace» y pega aquí el enlace copiado.</p><label>Enlace de Drive<input id="drive-image-url" type="url" placeholder="https://drive.google.com/file/d/…/view"></label><label>Descripción de la imagen<input id="drive-image-alt" placeholder="Personas reunidas en una asamblea"></label><button class="button" type="button" id="insert-drive-image">Insertar imagen</button><p id="drive-image-status" aria-live="polite"></p>';
  const driveUrl=value=>{try{const url=new URL(value),id=url.pathname.match(/\/file\/d\/([^/]+)/)?.[1]||url.searchParams.get('id');return id?`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`:''}catch{return''}};
  document.querySelector('#insert-drive-image').addEventListener('click',()=>{const url=driveUrl(document.querySelector('#drive-image-url').value),status=document.querySelector('#drive-image-status');if(!url){status.textContent='No reconozco ese enlace de Drive.';return}const alt=document.querySelector('#drive-image-alt').value.trim();editor.setRangeText(`\n![${alt}](${url})\n`,editor.selectionStart,editor.selectionEnd,'end');status.textContent='Imagen insertada en el artículo.';editor.focus();render()});
  const style=document.createElement('style');style.textContent='#publisher label{display:block;font-weight:700;margin:1rem 0}#publisher input,#publisher textarea,#publisher select{display:block;width:100%;font:inherit;padding:.7rem;margin-top:.3rem}.editor{min-height:24rem;font-family:ui-monospace,monospace;border-radius:0 0 .55rem .55rem}.editor-toolbar{position:sticky;top:0;z-index:2;display:flex;flex-wrap:wrap;gap:.35rem;padding:.6rem;background:#eef3ee;border:1px solid #aebcae;border-bottom:0;border-radius:.55rem .55rem 0 0}.editor-tool{border:1px solid #6b786d;border-radius:.35rem;background:#fff;padding:.45rem .65rem;font:inherit;font-weight:700;cursor:pointer}.editor-tool:hover,.editor-tool:focus{background:#163f2d;color:#fff}#md-preview img{max-width:100%;height:auto}#md-preview blockquote{border-left:.3rem solid #5c796a;margin:1rem 0;padding:.5rem 1rem;background:#f1f4f2}#md-preview .callout{border-left:.35rem solid #d99000;background:#fff3d6;padding:1rem;margin:1rem 0}#md-preview .callout strong{display:block}';document.head.append(style);render();
}
