const form=document.querySelector('#publisher');
if(form){
  const editor=form.elements.body,preview=document.querySelector('#md-preview');let imagePosition=0;
  const slugify=value=>value.toLocaleLowerCase('es').normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80);
  const escape=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
  const driveUrl=value=>{try{const url=new URL(value),id=url.pathname.match(/\/file\/d\/([^/]+)/)?.[1]||url.searchParams.get('id');return id?`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`:''}catch{return''}};
  const imageUrl=value=>driveUrl(value)||(/^https:\/\//.test(value)?value:'');
  const values=()=>Object.fromEntries(new FormData(form));
  const markdown=()=>{const data=values(),tags=data.tags.split(',').map(tag=>tag.trim()).filter(Boolean);return `---\ntitle: ${data.title.trim()}\nslug: ${slugify(data.title)}\ndate: ${data.date}\nsummary: ${data.summary.trim().replace(/\s+/g,' ')}\nauthor: ${data.author.trim()}\nstatus: ${data.status}\npriority: ${data.priority}\nimage: ${imageUrl(data.featuredImage||'')}\nimageAlt: ${(data.featuredImageAlt||'').trim()}\ntags: [${tags.join(', ')}]\n---\n\n${data.body.trim()}\n`};
  const inline=value=>escape(value).replace(/!\[([^\]]*)\]\((https:\/\/[^\s)]+)\)/g,'<img src="$2" alt="$1" loading="lazy">').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>');
  const renderBody=value=>{const html=[];let list=[],type='';const flush=()=>{if(list.length){html.push(`<${type}>${list.map(item=>`<li>${inline(item)}</li>`).join('')}</${type}>`);list=[];type=''}};for(const line of value.split(/\r?\n/)){if(!line.trim()){flush();continue}const heading=line.match(/^(#{2,4})\s+(.+)$/);if(heading){flush();html.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);continue}const item=line.match(/^[-*]\s+(.+)$/),numbered=line.match(/^\d+\.\s+(.+)$/);if(item||numbered){const next=item?'ul':'ol';if(type&&type!==next)flush();type=next;list.push((item||numbered)[1]);continue}flush();if(/^---+$/.test(line))html.push('<hr>');else if(line.startsWith('> [!IMPORTANTE]'))html.push(`<aside class="callout"><strong>Importante</strong>${inline(line.slice(15))}</aside>`);else if(line.startsWith('> '))html.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);else if(/^!\[/.test(line))html.push(`<figure>${inline(line)}</figure>`);else html.push(`<p>${inline(line)}</p>`)}flush();return html.join('')};
  const render=()=>{const data=values(),featured=imageUrl(data.featuredImage||'');preview.innerHTML=`<span class="pill">${escape(data.status)}</span><h2>${escape(data.title||'Sin título')}</h2><p>${escape(data.summary)}</p>${featured?`<figure class="featured-image"><img src="${escape(featured)}" alt="${escape(data.featuredImageAlt||'')}" loading="lazy"></figure>`:''}${renderBody(data.body)}`};
  const toolbar=document.createElement('div');toolbar.className='editor-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Formato del artículo');
  const imagePanel=document.createElement('div');imagePanel.className='image-panel';imagePanel.hidden=true;imagePanel.innerHTML='<strong>Insertar imagen dentro del artículo</strong><label>Enlace público de Drive o URL<input id="inline-image-url" type="url" placeholder="https://drive.google.com/file/d/…/view"></label><label>Descripción de la imagen<input id="inline-image-alt" placeholder="Describe brevemente lo que aparece"></label><div class="actions"><button class="button" type="button" id="confirm-inline-image">Insertar aquí</button><button class="button secondary" type="button" id="cancel-inline-image">Cancelar</button></div><p id="inline-image-status" aria-live="polite"></p>';
  const format=(action,...args)=>{const start=editor.selectionStart,end=editor.selectionEnd,selected=editor.value.slice(start,end);let text=selected;if(action==='image'){imagePosition=start;imagePanel.hidden=false;document.querySelector('#inline-image-url').focus();return}if(action==='wrap')text=`${args[0]}${selected||'texto'}${args[1]}`;if(action==='heading')text=`${args[0]}${selected||'Texto del título'}`;if(action==='lines')text=(selected||'Elemento').split(/\r?\n/).map(line=>`${args[0]}${line}`).join('\n');if(action==='numbered')text=(selected||'Elemento').split(/\r?\n/).map((line,index)=>`${index+1}. ${line}`).join('\n');if(action==='link'){const url=window.prompt('Pega el enlace completo (https://…)');if(!url)return;text=`[${selected||'texto del enlace'}](${url})`}if(action==='insert')text=args[0];editor.setRangeText(text,start,end,'select');editor.focus();render()};
  const tools=[['Título','heading','## '],['Subtítulo','heading','### '],['Negrita','wrap','**','**'],['Cursiva','wrap','*','*'],['Enlace','link'],['Imagen','image'],['Lista','lines','- '],['Numerada','numbered'],['Cita','lines','> '],['Aviso','insert','\n> [!IMPORTANTE] Escribe aquí el aviso\n'],['Separador','insert','\n---\n']];
  for(const [label,action,...args] of tools){const button=document.createElement('button');button.type='button';button.className='editor-tool';button.textContent=label;button.addEventListener('click',()=>format(action,...args));toolbar.append(button)}editor.before(toolbar);toolbar.after(imagePanel);
  const media=document.querySelector('.media-library');media.innerHTML='<h2>Imagen destacada</h2><p>Se utilizará como imagen principal del artículo. Pega un enlace público de Drive o una URL de imagen.</p><label>Enlace de la imagen destacada<input name="featuredImage" type="url" placeholder="https://drive.google.com/file/d/…/view"></label><label>Descripción accesible<input name="featuredImageAlt" placeholder="Personas reunidas en una asamblea"></label>';
  document.querySelector('#cancel-inline-image').addEventListener('click',()=>{imagePanel.hidden=true;editor.focus()});
  document.querySelector('#confirm-inline-image').addEventListener('click',()=>{const source=document.querySelector('#inline-image-url').value,url=imageUrl(source),status=document.querySelector('#inline-image-status');if(!url){status.textContent='Introduce un enlace válido de Drive o una URL de imagen.';return}const alt=document.querySelector('#inline-image-alt').value.trim();editor.setRangeText(`\n![${alt}](${url})\n`,imagePosition,imagePosition,'end');document.querySelector('#inline-image-url').value='';document.querySelector('#inline-image-alt').value='';imagePanel.hidden=true;editor.focus();render()});
  const steps=document.createElement('aside');steps.className='publishing-steps notice';steps.innerHTML='<h2>Cómo enviar el artículo</h2><ol><li>Completa el artículo y pulsa <strong>Descargar .md</strong>.</li><li>Abre la <a href="https://drive.google.com/drive/folders/1zU6Jx-HsPQi4S9xcMQXuXlZLCRUY7dKm" target="_blank" rel="noopener"><strong>carpeta «artículos» de Drive</strong></a>.</li><li>Sube allí el archivo <code>.md</code> descargado. La web lo recogerá automáticamente.</li></ol>';document.querySelector('.actions').after(steps);
  document.querySelector('#preview-md').addEventListener('click',render);form.addEventListener('input',render);
  const downloadStatus=document.createElement('p');downloadStatus.id='download-status';downloadStatus.setAttribute('aria-live','polite');document.querySelector('#download-md').closest('.actions').after(downloadStatus);
  const imageLoads=url=>new Promise(resolve=>{const image=new Image(),timer=setTimeout(()=>resolve(false),8000);image.onload=()=>{clearTimeout(timer);resolve(true)};image.onerror=()=>{clearTimeout(timer);resolve(false)};image.src=url});
  document.querySelector('#download-md').addEventListener('click',async()=>{if(!form.reportValidity())return;const data=values(),urls=[imageUrl(data.featuredImage||''),...[...data.body.matchAll(/!\[[^\]]*\]\((https:\/\/[^\s)]+)\)/g)].map(match=>match[1])].filter(Boolean);downloadStatus.textContent=urls.length?'Comprobando que las imágenes sean accesibles…':'Preparando el archivo…';const checks=await Promise.all(urls.map(imageLoads));if(checks.includes(false)){downloadStatus.textContent='No se ha descargado: al menos una imagen no es pública o no puede cargarse. Revisa sus enlaces.';return}const blob=new Blob([markdown()],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${data.date}-${slugify(data.title)}.md`;anchor.click();URL.revokeObjectURL(url);downloadStatus.textContent='Archivo descargado. Ahora súbelo a la carpeta «artículos» de Drive.'});
  const style=document.createElement('style');style.textContent='#publisher label{display:block;font-weight:700;margin:1rem 0}#publisher input,#publisher textarea,#publisher select{display:block;width:100%;font:inherit;padding:.7rem;margin-top:.3rem}.editor{min-height:24rem;font-family:ui-monospace,monospace;border-radius:0 0 .55rem .55rem}.editor-toolbar{position:sticky;top:0;z-index:2;display:flex;flex-wrap:wrap;gap:.35rem;padding:.6rem;background:#eef3ee;border:1px solid #aebcae;border-bottom:0;border-radius:.55rem .55rem 0 0}.editor-tool{border:1px solid #6b786d;border-radius:.35rem;background:#fff;padding:.45rem .65rem;font:inherit;font-weight:700;cursor:pointer}.editor-tool:hover,.editor-tool:focus{background:#163f2d;color:#fff}.image-panel{border:1px solid #aebcae;border-top:0;border-radius:0 0 .55rem .55rem;padding:1rem;background:#f7faf7}.image-panel[hidden]{display:none}.publishing-steps{margin-top:1rem}.featured-image img,#md-preview img{display:block;max-width:100%;height:auto;border-radius:.4rem}#md-preview blockquote{border-left:.3rem solid #5c796a;margin:1rem 0;padding:.5rem 1rem;background:#f1f4f2}#md-preview .callout{border-left:.35rem solid #d99000;background:#fff3d6;padding:1rem;margin:1rem 0}#md-preview .callout strong{display:block}';document.head.append(style);render();
}
